name: Ping Render API every 15 minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # 매 15분마다 UTC 기준
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Render API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://realestateapi-4f6d.onrender.com/ || echo "Request failed"
